language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install xml2rfc
# command to run tests, e.g. python setup.py test
script: make upload

env:
 global:
 - GH_REF: github.com/rtcweb-wg/security-arch.git
 - secure: "MqWMRIJ+9AVNhPPkplnnF4nIVgOqzNPvhLD4ghxkf86U4KYBzlxZj12WK9b50XdJGsAZdMz2V4iuZ5yYikX0aSuUcR9hvwPsLMqeRpSssNrLI29RQBihQzhn9/6j9LK82Iv/hs69owFhqUBHxi5PtsYtfokCkLas8gtJdKj5hZo="

